function plot_exampleSleep_trial_Neonate(filname)
%% READ ME
%This function plots the data generated by the single trial loaded in
%'filname' and includes, behavior, EMG, HbT and LFP
%Subscripts: brewermap
load(filname);
underScores=strfind(filname,'_');
load([filname(1:underScores(end)) 'TrainingData_003.mat']);
load([filname(1:underScores(end)) 'SleepScoringData.mat'],'IOS','Spectrograms');
%% Filter for EMG
[z,p,k]=butter(3,[300 5000]/(0.5*RawData.an_fs),'bandpass');
[sos_EMG,g_EMG]=zp2sos(z,p,k);
%% Filter for ball velocity
[z,p,k]=butter(3,10/(0.5*RawData.an_fs),'low');
[sos_Ball,g_Ball]=zp2sos(z,p,k);
%% Filter for LFP
[z,p,k]=butter(3,[1 100]/(0.5*RawData.an_fs),'bandpass');
[sos_LFP,g_LFP]=zp2sos(z,p,k);

%% Filter for HbT
[z,p,k]=butter(5,[0.1 1]/(0.5*RawData.dal_fr),'bandpass');
[sos_HbT,g_HbT]=zp2sos(z,p,k);

[b_HbT,a_HbT]=zp2tf(z,p,k);
%% Constants
an_Time=(1:length(RawData.vBall))/20000;
emg_Kernel=normpdf((1:(2*RawData.an_fs)),(RawData.an_fs),(0.05*RawData.an_fs));
%% Hypnogram colormaps
% tempMap=brewermap(12,'RdBu');
tempMap_1=brewermap(11,'RdGy');
tempMap_2=brewermap(11,'RdBu');
colors(1,:)=tempMap_2(2,:);
colors(2,:)=tempMap_2(9,:);
colors(3,:)=tempMap_1(7,:);
colors(4,:)=tempMap_1(9,:);
% colors(1,:)=tempMap(2,:);
% colors(2,:)=tempMap(4,:);
% colors(3,:)=tempMap(8,:);
% colors(4,:)=tempMap(10,:);
% colors(5,:)=[1 1 1];


%% Define behavior state of each bin
ActiveAwake=strcmpi(TrainingTable.behavState,'Active Awake');
QuiescentAwake=strcmpi(TrainingTable.behavState,'Quiescent Awake');
ActiveAsleep=strcmpi(TrainingTable.behavState,'Active Asleep');
QuiescentAsleep=strcmpi(TrainingTable.behavState,'Quiescent Asleep');

%% Convert logicals in to numeric values in single array
tempHypnogram=[];
tempHypnogram(1:length(TrainingTable.behavState))=NaN;
tempHypnogram(ActiveAwake)=4;
tempHypnogram(ActiveAsleep)=1;
tempHypnogram(QuiescentAwake)=3;
tempHypnogram(QuiescentAsleep)=2;
tempHypnogram(isnan(tempHypnogram))=5;

hypnoTime=(0:length(tempHypnogram))*5;

%% plot Hypnogram
figure(600);
ax1=subplot(12,4,(1:4));
imagesc(hypnoTime,(0:1),tempHypnogram);theax=gca;colormap(theax,colors);caxis([1 5]);%bar(hypnoTime,barHeight,1);
L=colorbar('Ticks',[1.5:1:(size(colors,1)+0.5)],'TickLabels',{'REM','NREM','Quiescent','Active'});
L.Label.String='Arousal State';
L.Position=[0.91 0.875 0.015 0.05];
anLabel=strrep(filname(1:(underScores(2)-1)),'_', ' ');
ylabel('Arousal State');
theLabel=get(gca,'YLabel');
set(theLabel,'rotation',0,'VerticalAlignment','middle','HorizontalAlignment','right');
yticks([]);
xticks([]);
xlim([0 300]);

%% plot ball velocity
tempVel=filtfilt(sos_Ball,g_Ball,RawData.vBall);
maxvel=2*pi*0.06*10;
maxVol=10; % maximum voltage output (read from USDigital device)
rate=maxvel/maxVol;
velocity=tempVel*rate*100; %Velocity is in cm/sec
velocity=velocity+0.157;
% figure(601);
 ax2=subplot(12,4,(5:8));
plot(an_Time,abs(velocity),'k');
ylabel('Ball Velocity (cm/s)');
theLabel=get(gca,'YLabel');
set(theLabel,'rotation',0,'VerticalAlignment','middle','HorizontalAlignment','right');
xticks([]);
xlim([0 300]);

%% plot EMG signal 
% figure(603);
theEMG=filtfilt(sos_EMG,g_EMG,(RawData.MUA/10000));
 ax3=subplot(12,4,(9:16));
% yyaxis left; plot(an_Time,log10(conv((theEMG*1000000).^2,emg_Kernel,'same')));
% ylabel('EMG Power (log units)');
% theLabel=get(gca,'YLabel');
% set(theLabel,'rotation',0,'VerticalAlignment','middle','HorizontalAlignment','right');

% yyaxis right; 
plot(an_Time,(theEMG*1000000),'k');
theaxes=gca;
theaxes.YColor='black';
ylabel('EMG [300-5000Hz] (uV)');
theLabel=get(gca,'YLabel');
% set(theLabel,'rotation',0,'VerticalAlignment','middle','HorizontalAlignment','left');
set(theLabel,'rotation',0,'VerticalAlignment','middle','HorizontalAlignment','right');
xticks([]);
xlim([0 300]);
%% plot LFP Signal
% theLFP=filtfilt(sos_LFP,g_LFP,(RawData.Neuro/1000));
ax4=subplot(12,4,(17:24));
 plot(an_Time,log10(conv((theEMG*1000000).^2,emg_Kernel,'same')));
ylabel('EMG Power (log units)');
theLabel=get(gca,'YLabel');
set(theLabel,'rotation',0,'VerticalAlignment','middle','HorizontalAlignment','right');
ylim([-0.5 5]);
xticks([]);
% plot(an_Time,(theLFP*1000000),'k');
% theaxes=gca;
% theaxes.YColor='black';
% ylabel('Hippocampus LFP [1-100hz] (uV)');
% theLabel=get(gca,'YLabel');
% set(theLabel,'rotation',0,'VerticalAlignment','middle','HorizontalAlignment','right');
% xticks([]);
% ylim([-300 300]);

%% plot \Delta HbT
baseline_HbT=mean(IOS.forepaw.dHbT(1:(30*RawData.dal_fr)),2);
hbt_Time=(1:length(IOS.forepaw.dHbT))/RawData.dal_fr;
% figure(604);
 ax5=subplot(12,4,(29:40));
% yyaxis left;
plot(hbt_Time,(IOS.forepaw.dHbT),'r');%-baseline_HbT
ylabel('\DeltaHbT (\muM)');
% theaxes=gca;
% theaxes.YColor='red';
theLabel=get(gca,'YLabel');
set(theLabel,'rotation',0,'VerticalAlignment','middle','HorizontalAlignment','right');
xticks([]);
ylim([-50 100]);
xlim([0 300]);

% yyaxis right;
% % plot(hbt_Time,filtfilt(sos_HbT,g_HbT,(IOS.forepaw.dHbT-baseline_HbT)),'m');
% plot(hbt_Time(2:end),diff(IOS.forepaw.dHbT),'m');
% ylabel('\DeltaHbT [0.1-1Hz] (\muM)');
% theaxes=gca;
% theaxes.YColor='magenta';
% theLabel=get(gca,'YLabel');
% set(theLabel,'rotation',0,'VerticalAlignment','middle','HorizontalAlignment','left');
% hold on; plot(hbt_Time,filter(b_HbT,a_HbT,IOS.forepaw.dHbT-baseline_HbT),'-k');
% ylim([-6 6]);

%% Semi-log LFP Spectrogram
% figure(605);
 ax6=subplot(12,4,(41:48)); 
semilog_imagesc(Spectrograms.FiveSec.T5,Spectrograms.FiveSec.F5,Spectrograms.FiveSec.S5_Norm,'y'); thespec=gca;
colormap(thespec,parula(200));caxis([-100 100]); c=colorbar();
c.Label.String='\DeltaP/P_o (%)';
c.Position=[0.91 0.11 0.015 0.12];
theaxes=gca;
theaxes.YColor='black';
ylabel('Frequency (Hz)');
xlabel('Time (sec)');
ylim([1 100]);
xlim([0 300]);
xticks([0, 60, 2*60, 3*60, 4*60, 5*60]);

%% plot formatting
 linkaxes([ax1,ax2,ax3,ax4,ax5,ax6],'x'); xlim([0 300]);%,ax4
anStr=filname(1:(underScores(2)-1));
anName=strrep(anStr,'_',' ');
timeStr=filname((underScores(4)+1):(underScores(7)-1));
timeLabel=strrep(timeStr,'_',' ');
sgtitle(['P15 ' anName ' ' timeLabel]);
%% Pixelwise Images
[pixelwise_colormap]=buildcmap_enhance_pos_neg_difference('bcwyr');
timeInds=[65,162,220, 290];
frameInds=floor(timeInds*RawData.dal_fr);
figure(606)
for count=1:length(frameInds)
[theFrame,theROI]=reconstruct_Pixelwise_Image(IOS.Pixelwise.dHbT,IOS.Pixelwise.PixelMap,IOS.forepaw.PixelMap,frameInds(count));
% subplot(12,4,([(20+count) (24+count)]));
subplot(1,4,count);
imagesc(theFrame);axis square; 
img_ax=gca;
colormap(img_ax,pixelwise_colormap); caxis([-100 100]);
hold on;
plot(theROI{1}(:,2),theROI{1}(:,1),'white','LineWidth',2);
axis image; axis xy; yticks([]);xticks([]);

title(['T= ' num2str(timeInds(count)) ' seconds']);
if count==length(frameInds)
    theBar=colorbar();
    theBar.Label.String=('\DeltaHbT (\muM)');
    theBar.Position=[0.91 0.455 0.015 0.12];
    ylabel('Lateral');
    xlabel('Caudal');
end
end
end
